apiVersion: v1
kind: Service
metadata:
  name: kafka-connect-svc
  namespace: kafka-platform
  labels:
    app: kafka-connect
    component: kafka-platform
spec:
  selector:
    app: kafka-connect
  ports:
    - name: http
      port: 8083
      targetPort: 8083
  type: ClusterIP
