apiVersion: v1
kind: Service
metadata:
  name: kafka-schema-registry
  namespace: kafka-platform
  labels:
    app: kafka-schema-registry
    component: kafka-platform
spec:
  selector:
    app: kafka-schema-registry
  ports:
    - name: http
      port: 8081
      targetPort: 8081
  type: ClusterIP
