# ==============================================================================
# Notes:
#   - Password must be minimum12characters
# ==============================================================================
apiVersion: v1
kind: Secret
metadata:
  name: nifi-credentials
  namespace: kafka-platform
type: Opaque
stringData:
  username: "admin"
  # Must be at least 12 characters
  password: "minimum12characters"